import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>Upgrade your development today</h2>
        <p>Learn web development using latest tech.</p>
      </main>
    </div>
  );
}
